/// Continuous calendar, Dec 2009 - Dec 2011. Marked as the date table.
table dim_date
	lineageTag: a476fdcd-fb00-5087-9834-bc32786a4c79
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 89dc9801-e437-5236-84fd-cc4d85ec8071
		summarizeBy: none
		sourceColumn: date

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = User

	column year
		dataType: int64
		formatString: 0
		lineageTag: e164ec2d-28ba-51f6-abd7-41beed0f9c3c
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = User

	column quarter
		dataType: string
		lineageTag: e77dbb2b-dc97-50a1-b141-7a5d0061b427
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = User

	column month_num
		dataType: int64
		isHidden
		lineageTag: 6048a7df-1bfc-5276-a537-b97df925d03d
		summarizeBy: none
		sourceColumn: month_num

		annotation SummarizationSetBy = User

	column month_name
		dataType: string
		lineageTag: 7862578b-9719-5c90-a733-ef2d07c33fdd
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_num

		annotation SummarizationSetBy = User

	column month_start
		dataType: dateTime
		formatString: mmm yyyy
		lineageTag: bc14a611-cd60-5ec7-bdbe-63adf1700581
		summarizeBy: none
		sourceColumn: month_start

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = User

	column year_month
		dataType: string
		lineageTag: ab71ac36-1bd9-5638-ab9b-5d25a366a6e2
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = User

	column week
		dataType: int64
		lineageTag: 15ece203-9dda-5cbf-80e3-d5d68098a597
		summarizeBy: none
		sourceColumn: week

		annotation SummarizationSetBy = User

	column weekday_num
		dataType: int64
		isHidden
		lineageTag: 5d86647b-28d2-566d-b475-6210bb91782d
		summarizeBy: none
		sourceColumn: weekday_num

		annotation SummarizationSetBy = User

	column weekday_name
		dataType: string
		lineageTag: 2c568d32-ad8f-56b1-968f-0047d998a7dd
		summarizeBy: none
		sourceColumn: weekday_name
		sortByColumn: weekday_num

		annotation SummarizationSetBy = User

	column is_partial_month
		dataType: boolean
		lineageTag: 0f75547a-aac2-5ba1-8db4-6dcd09f1fb0d
		summarizeBy: none
		sourceColumn: is_partial_month

		annotation SummarizationSetBy = User

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"date", type date}, {"year", Int64.Type}, {"quarter", type text}, {"month_num", Int64.Type}, {"month_name", type text}, {"month_start", type date}, {"year_month", type text}, {"week", Int64.Type}, {"weekday_num", Int64.Type}, {"weekday_name", type text}, {"is_partial_month", type logical}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
